site_name: Note taking with MkDocs Material
site_description: A simple note-taking application using MkDocs Material.
site_author: Alan Heslop
site_url: https://sitename.example.com
theme:
  name: material
  font:
    text: Merriweather Sans
    code: Red Hat Mono
  logo: assets/a.png
  favicon: assets/a.png
  features:
    - navigation.footer
  palette:
    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange
      # Dark Mode

    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: deep purple

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
            - name: mermaid
              class: mermaid
              format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details

extra:
  social:
    - icon: simple/github
      link: http://test.com
    - icon: simple/google
      link: http://test.com
    - icon: fontawesome/brands/linkedin
      link: http://test.com
    - icon: fontawesome/brands/gitlab
      link: http://test.com

copyright: Copyright &copy; 2024 Alan Heslop

nav:
  - My Docs:
      - Welcome: index.md
      - Admonitions: admonitions.md
  - Examples:
      - Code Examples: code-examples.md
      - Content Tabs: content-tabs.md
      - Diagrams: diagram-examples.md
  - Test: test.md
